"""
Slicer Branch Tracer Prototype Skeleton
=======================================

This is a Slicer-Python starting point for using a route JSON generated by
bronchoscopy_airway_vtk_adapter.py.

It is intended to be run inside 3D Slicer's Python environment, not standard
Python. It has not been executed in this container because Slicer is not installed
here.

Assumptions
-----------
- A CT volume is already loaded in Slicer, or you load one separately.
- `Network model.vtk` can be loaded as a model node for 3D airway display.
- `route_json_path` points to a JSON generated by the adapter.

What it does
------------
- Creates a MarkupsCurve for the airway route.
- Creates a moving fiducial for the current bronchoscope position.
- Provides `set_route_index(i)` to update:
    - the moving fiducial
    - standard slice crosshairs
    - optional custom slice orientations from the route frame

Use this as a module/controller skeleton rather than final production code.
"""

import json

import slicer
import vtk


class BranchTracerController:
    def __init__(self, route_json_path, network_model_path=None):
        self.route_json_path = route_json_path
        self.network_model_path = network_model_path
        self.route = self._load_route(route_json_path)
        self.points = self.route["route"]["points_ras"]
        self.frames = self.route["route"].get("frames", [])
        self.current_index = 0
        self.route_curve_node = None
        self.current_fiducial_node = None
        self.network_model_node = None

    @staticmethod
    def _load_route(path):
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    def load_network_model(self):
        if not self.network_model_path:
            return None
        success, node = slicer.util.loadModel(self.network_model_path, returnNode=True)
        if not success:
            raise RuntimeError(f"Could not load network model: {self.network_model_path}")
        self.network_model_node = node
        node.SetName("Airway network")
        display = node.GetDisplayNode()
        if display:
            display.SetOpacity(0.25)
        return node

    def create_route_curve(self):
        curve = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsCurveNode", "Planned airway route")
        curve.SetCurveTypeToLinear()
        for p in self.points:
            curve.AddControlPoint(vtk.vtkVector3d(float(p[0]), float(p[1]), float(p[2])))
        self.route_curve_node = curve
        display = curve.GetDisplayNode()
        if display:
            display.SetLineThickness(0.4)
        return curve

    def create_current_position_marker(self):
        fid = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLMarkupsFiducialNode", "Current bronchoscope position")
        p = self.points[0]
        fid.AddControlPoint(vtk.vtkVector3d(float(p[0]), float(p[1]), float(p[2])))
        self.current_fiducial_node = fid
        return fid

    def setup(self):
        if self.network_model_path:
            self.load_network_model()
        self.create_route_curve()
        self.create_current_position_marker()
        self.set_route_index(0)

    def set_route_index(self, index):
        index = max(0, min(int(index), len(self.points) - 1))
        self.current_index = index
        p = self.points[index]

        if self.current_fiducial_node is not None:
            self.current_fiducial_node.SetNthControlPointPosition(0, float(p[0]), float(p[1]), float(p[2]))

        # Jump standard slice views to the current airway point.
        slicer.modules.markups.logic().JumpSlicesToLocation(float(p[0]), float(p[1]), float(p[2]), True)

        # If frames are present, use them for airway-relative slice planes.
        if self.frames:
            frame = self.frames[index]
            planes = frame.get("ct_planes", {})
            if "airway_cross_section" in planes:
                self._set_slice_to_plane("Red", planes["airway_cross_section"])
            if "airway_long_axis_normal" in planes:
                self._set_slice_to_plane("Yellow", planes["airway_long_axis_normal"])
            if "lesion_directed_long_axis" in planes:
                self._set_slice_to_plane("Green", planes["lesion_directed_long_axis"])
            elif "airway_long_axis_binormal" in planes:
                self._set_slice_to_plane("Green", planes["airway_long_axis_binormal"])

    @staticmethod
    def _set_slice_to_plane(slice_name, plane):
        """Set a Slicer slice view orientation from a route JSON plane definition.

        The adapter exports plane axes in RAS. The matrix columns are:
            column 0 = x axis
            column 1 = y axis
            column 2 = slice normal
            column 3 = origin
        """
        lm = slicer.app.layoutManager()
        widget = lm.sliceWidget(slice_name)
        if widget is None:
            return
        slice_node = widget.mrmlSliceNode()
        origin = plane["origin_ras"]
        x_axis = plane["x_axis_ras"]
        y_axis = plane["y_axis_ras"]
        normal = plane["normal_ras"]

        m = vtk.vtkMatrix4x4()
        axes = [x_axis, y_axis, normal, origin]
        for col, vec in enumerate(axes):
            for row in range(3):
                m.SetElement(row, col, float(vec[row]))
        m.SetElement(3, 0, 0.0)
        m.SetElement(3, 1, 0.0)
        m.SetElement(3, 2, 0.0)
        m.SetElement(3, 3, 1.0)
        slice_node.SetSliceToRAS(m)
        slice_node.Modified()

    def current_bifurcation_prompt(self):
        """Return a branch-decision object if the current index is near a bifurcation.

        The adapter includes `route_point_index`, which marks the route point at
        which the corresponding decision edge begins.
        """
        decisions = self.route.get("bifurcation_decisions", [])
        for d in decisions:
            idx = d.get("route_point_index")
            if idx is not None and abs(int(idx) - self.current_index) <= 1:
                return d
        return None


# Example inside Slicer:
#
# controller = BranchTracerController(
#     route_json_path=r"/path/to/route_to_lesion.json",
#     network_model_path=r"/path/to/Network model.vtk",
# )
# controller.setup()
# controller.set_route_index(50)
